export enum FormTypes {
  TEXT = 'TEXT',
  NUMBER = 'NUMBER',
  DATE = 'DATE',
  CHECKBOX = 'CHECKBOX',
  SINGLE_SELECT = 'SINGLE_SELECT',
  MULTI_SELECT = 'MULTI_SELECT',
  TEXTAREA = 'TEXTAREA',
  EMAIL = 'EMAIL',
  SWITCH = 'SWITCH',
  EDITOR = 'EDITOR',
  PASSWORD = 'PASSWORD',
}
